/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "main.h"
#include <stdio.h>

struct PWR_ PWR = {
    .CR = (uint32_t*)0x40007000,
    .CSR = (uint32_t*)0x40007004,

};

#define PWR_ON() (*(PWR.CR) |= (1U<<14))

struct FLASH_ FLASH = {
	 .ACR= (uint32_t *)0x40023c00
};

#define I2C1_BASE_ADDR (0x40005400UL) // Example base address for I2C1
#define I2C1_ ((I2C_TypeDef *) I2C1_BASE_ADDR)


struct i2ctypedef I2C1={
		.frequency=36,
		.intance=I2C1_,
		.mode=I2C_MASTER
};
//struct SYSCFG_ SYSCFG = {
//	.EXTICR1 = (uint32_t*)0x40013808
//};

//function definitions
void sysclk_config();
uint8_t get_pos(uint16_t pin);
void GPIO_pin_init(GPIO_TypeDef *GPIOx,uint16_t pin,enum _mode mode);

char*msg ="hello World";
uint8_t addr;
i2c_err_t xSTATUS;
int main(void)
{
	sysclk_config();
	GPIOx_init();
	I2C1_INIT(&I2C1);
	i2c_err_t Status = M_I2C_WRITE((char*)msg,I2C1_,0x08);
//	Status=M_get_addr(I2C1_,&addr);

	if(Status != I2C_OK){
		printf("NO valid address found");
	}else{
		printf("slave found at : %d \n",addr);
		 M_I2C_WRITE((char*)"a",I2C1_,0x08);
	}
//	I2C1_Slave_Init(0x13,I2C1_);
//	I2C1_Slave_Loop(I2C1_);
    /* Loop forever */
	for(;;);
}

void sysclk_config(){

	RCC->CR |=HSEON;//HSE clock enable
	while(!(RCC->CR & HSERDY)); // wait for HSE clock ready flag


	RCC->APB1ENR |=I2C1_EN;// enable 12c1 interface

	RCC->APB1ENR |=PWR_CLK; //Power interface clock enable
	PWR_ON();

	*(FLASH.ACR) |= ICEN | DCEN | PRFTEN | LATENCY ; //configure flash for 5cpu cycle latency

	RCC->PLLCFGR |=(PLLM | PLLN | PLLSRC | PLLP | PLLQ); //sets clock frequency
	RCC->CR |= PLLON;//Main PLL (PLL) enable

	while(!(RCC->CR & PLLRDY)); //wait for Main PLL (PLL) clock ready

	RCC->CFGR |=  MAIN_PRE;
	RCC->CFGR &= ~CLOCK_SWITCH; // clear switch clock bit
	RCC->CFGR |= PLL_AS_MAIN; // set pll clock as main clock

	while((RCC->CFGR & SWITCH_STATUS) != (2U << 2)); // verify the clock is switched or not

}
//#define SYSCFGEN (1U <<14)
//void enable_interrupt(){
//	*(RCC.APB2ENR) |=SYSCFGEN; //enable syscfg clock
//
//	*(SYSCFG.EXTICR1) &= ~(0xf <<0); //selects gpioa for extio
//
//	*EXTI_RTSR |= (1U <<0); //rising edge trigger
//	*EXTI_FTSR |= (1U <<0); // falling edge trigger
//	*EXTI_IMR |= (1U << 0); //unmask interrupt for exti0
//
//	*NVIC_IPR1 = (2u<<20); //SET PRIORITY FOR INTERRRUPT
//	*NVIC_ISER0 |= (1U << 6); // ENABLR EXTI0 (IRQ6)
//}

uint8_t get_pos(uint16_t pin){
	uint8_t i=0;
	while(pin > 1){
		pin=pin/2;
		i++;
	}
	return i;
}
void GPIOx_init(){
	RCC->AHB1ENR |= GPIOA_EN |GPIOB_EN; //enable clock for GPIOA and GPIOB

	GPIO_pin_init(I2C1_PORT, I2C1_SDA, AF_PP);
	GPIO_pin_init(I2C1_PORT, I2C1_SCL, AF_PP);
//	GPIO_pin_init(LED_PORT,LED_PIN,OUTPUT_NOPULL);
}

void GPIO_pin_init(GPIO_TypeDef *GPIOx,uint16_t pin,enum _mode mode){
	uint8_t pos=get_pos(pin);
	if(mode == AF_PP){
	GPIOx->MODER |= (_AF << (2*pos)); // selects gpio mode
	GPIOx->OTYPER |= (1U << pos); // 1 for open drain 0 for push pull
	GPIOx->PUPDR |= (_PU << (2*pos)); // pull up or pull down

	uint8_t af_index = (pos > 7)? 1:0;
	GPIOx->AFR[af_index] |= (4U << ((pos % 8)  *4)); //set pin to alternate function
	}else if(mode == INPUT_NOPULL){
		GPIOx->MODER |= (_INPUT << (2*pos));
		GPIOx->PUPDR |= (_PP << (2*pos)); // pull up or pull down
	}else if(mode == OUTPUT_NOPULL){
		GPIOx->MODER |= (_OUTPUT << (2*pos));
		GPIOx->PUPDR |= (_PP << (2*pos)); // pull up or pull down

	}else if(mode == OUTPUT_PU){
		GPIOx->MODER |= (_INPUT << (2*pos));
		GPIOx->PUPDR |= (_PU << (2*pos)); // pull up or pull down
	}else if(mode == INPUT_PU){
		GPIOx->MODER |= (_INPUT << (2*pos));
		GPIOx->PUPDR |= (_PU << (2*pos)); // pull up or pull down
	}
}
